export const ADD_FAMILY_SETTINGS = "ADD_FAMILY_SETTINGS";
export const FAMILY_DATA_LOADING = "FAMILY_DATA_LOADING";
export const ADD_FAMILY_SUCCESS = "ADD_FAMILY_SUCCESS";

export const ADD_USER_SETTINGS = "ADD_USER_SETTINGS";
export const USER_DATA_LOADING = "USER_DATA_LOADING";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";

export const ADD_ADDON_TO_VIEW = "ADD_ADDON_TO_VIEW";

export const ADD_ADDON_TARGETED = "ADD_ADDON_TARGETED";
