export const USER_ADD_SETTINGS = "USER_ADD_SETTINGS";
export const USER_DATA_LOADING = "USER_DATA_LOADING";
export const USER_ADD_DATA_SUCCESS = "USER_ADD_DATA_SUCCESS";
export const USER_POST_NEW_TASK = "USER_POST_NEW_TASK";
export const USER_POST_NEW_TASK_SUCCESS = "USER_POST_NEW_TASK_SUCCESS";

export const FAMILY_ADD_SETTINGS = "FAMILY_ADD_SETTINGS";
export const FAMILY_DATA_LOADING = "FAMILY_DATA_LOADING";
export const FAMILY_ADD_DATA_SUCCESS = "FAMILY_ADD_DATA_SUCCESS";
export const FAMILY_POST_NEW_TASK = "FAMILY_POST_NEW_TASK";
export const FAMILY_POST_NEW_TASK_SUCCESS = "FAMILY_POST_NEW_TASK_SUCCESS";

export const ADD_ADDON_TO_VIEW = "ADD_ADDON_TO_VIEW";
export const REMOVE_ADDON_FROM_VIEW = "REMOVE_ADDON_FROM_VIEW";

export const ADD_ADDON_TARGETED = "ADD_ADDON_TARGETED";
