export const ADD_FAMILY_DATA = "ADD_FAMILY_DATA";
export const FAMILY_DATA_LOADING = "FAMILY_DATA_LOADING";

export const ADD_USER_DATA = "ADD_USER_DATA";
export const USER_DATA_LOADING = "USER_DATA_LOADING";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";

export const ADD_ADDON_TARGETED = "ADD_ADDON_TARGETED";
